<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-14 at 01:01:00.
 */
class MongoDbCollectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MongoDbCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new MongoDbCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MongoDbCollection::insertRecord
     * @todo   Implement testInsertRecord().
     */
    public function testInsertRecord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MongoDbCollection::clear
     * @todo   Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
