<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-14 at 00:52:49.
 */
class UserModelCollectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserModelCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $dm = new DataManager();
        $dbConnection = $dm->getDatabaseConnection();
        $this->object = new UserModelCollection($dbConnection);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserModelCollection::getMyFriends
     * @todo   Implement testGetMyFriends().
     */
    public function testGetMyFriends() {
        $result = $this->object->getMyFriends(20);
        $this->assertEquals(is_object($result),true); 

    }

    /**
     * @covers UserModelCollection::getMyFriendsOfFriends
     * @todo   Implement testGetMyFriendsOfFriends().
     */
    public function testGetMyFriendsOfFriends() {
        $result = $this->object->getMyFriendsOfFriends(1);
        $this->assertEquals(is_array($result),true);
    }

    /**
     * @covers UserModelCollection::getSuggestedFriends
     * @todo   Implement testGetSuggestedFriends().
     */
    public function testGetSuggestedFriends() {
        $result = $this->object->getSuggestedFriends(20);
        $this->assertEquals(is_array($result),true);
    }

}
